name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project - nightly

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: rustup update nightly && rustup default nightly
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
